apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-b
  namespace: tenant-b
  labels:
    app: webapp-b
    tenant: tenant-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-b
  template:
    metadata:
      labels:
        app: webapp-b
        tenant: tenant-b
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: httpd
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-b-service
  namespace: tenant-b
spec:
  selector:
    app: webapp-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-b-ingress
  namespace: tenant-b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: tenant-b.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-b-service
            port:
              number: 80