apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-a
  namespace: argocd
spec:
  project: tenant-project
  source:
    repoURL: https://github.com/your-org/Secure-Multi-Tenant-Kubernetes-Platform
    targetRevision: HEAD
    path: tenants/tenant-a
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true